### ISSUE TITLE
A summarized checklist might be helpful

### ISSUE THREAD

**Issue by LKWLaLa** [learn-co-curriculum/rails-guided-project-module-2#4]
The README is currently chock full of details and long explanations, which is great - however, I actually find it a little overwhelming to read.  This is sort of a catch 22...  we want to provide the info for the struggling students, but I think too much info might make them shut down.  Just a thought - what if, in addition to the detailed README, there could be a very simple, step by step checklist, with checkboxes.   Something concrete to help students know they've covered all their bases.  Just for example:

1. - [ ]  Create User model, Users Controller, and users table
2.  - [ ]  Using your knowledge of sessions and bcrypt, allow a user to sign in and out
3.   - [ ] Display user information on a user show page, when you navigate to `localhost:3000/users/:id`
4.   - [ ] ...

Then, if they are struggling with a particular task, they can refer to the README for more information.

Thoughts?

**Comment by alexgriff** [comment]
Yeah something like this is probably the best way to balance this problem
